account/urls.py
from django.urls import path, include
from account import views


app_name = "account"

urlpatterns = [
    path("", include("django.contrib.auth.urls")),
    path("profile/create/", views.ProfileCreateView.as_view(), name="profile_create"),
    path(
        "profile/<int:pk>/detail/",
        views.ProfileDetailView.as_view(),
        name="profile_detail",
    ),
    path("profile/signup/", views.SignupView.as_view(), name="signup"),
    path("profile/login/", views.CustomLoginView.as_view(), name="login"),
    path("profile/logout/", views.LogoutView.as_view(), name="logout"),
]

core/urls.py
from django.urls import path
from core import views

app_name = "core"
 
urlpatterns = [
    path("", views.HomeView.as_view(), name="home"),
    path("about/", views.AboutView.as_view(), name="about"),
    # product
    path("products/", views.ProductListView.as_view(), name="product_list"),
    path("products/create/", views.ProctCreateView.as_view(), name="product_create"),
    path("products/<int:pk>/", views.ProductDetailView.as_view(), name="product_detail"),
    path("products/find/", views.FindProductView.as_view(), name="find_product"),
    path("products/<int:pk>/update/", views.ProductUpdateView.as_view(), name="product_update"),
    path("products/<int:pk>/delete/", views.ProductDeleteView.as_view(), name="product_delete"),
    # feedback
    path("feedback/create", views.FeedbackCreateView.as_view(), name="feedback_create"),
    path("feedback/<int:pk>/detail/", views.FeedbackDetailView.as_view(), name="feedback_detail"),
     # Wishlist
    path("wishlists/add/product/<int:pk>/", views.AddToWishlistView.as_view(), name="add_to_wishlist"),
    path("wishlists/create/", views.WishlistCreateView.as_view(), name="wishlist_create"),
    path("wishlists/", views.WishlistListView.as_view(), name="wishlist_list"),
    #add to cart
    path("cart/add/product/<int:pk>/", views.AddToCartView.as_view(), name="add_to_cart"),
    #review
    path("reviews/add/product/<int:pk>/", views.ReviewCreatView.as_view(), name="review_create"),
    path("reviews/product/review/<int:pk>/", views.ReviewListView.as_view(), name="review_list"),

  
        

]

ecart/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("core.urls", namespace="core")),
    path("accounts/", include("account.urls", namespace="account")),
    path("", include("django.contrib.auth.urls")),

]
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

templates/includes/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark ">
  <div class="container-fluid">
    <div class="logo me-3">
      <div class="d-flex justify-content-center align-item-center">
        <div>
          <i
            class="fa-solid fa-cart-shopping display-2 text-success m-1"
            style="font-size: 22px"
          ></i>
        </div>
        <div>
          <h1 class="text-success" style="font-size: 22px">E-cart</h1>
        </div>
      </div>
      <div class="logo-text d-flex justify-content-center align-items-center">
        <p class="text-success mt-1" style="font-size: 10px">
          E for Easy to shopping
        </p>
      </div>
    </div>
    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse  navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="http://127.0.0.1:8000">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link text-white" href="#">About Us</a>
        </li>
        <li class="nav-item">
          <a class="nav-link text-white" href="#">Contact Us</a>
        </li>
        <li class="nav-item">
          <a class="nav-link text-white" href="http://127.0.0.1:8000/products/">Products</a>
        </li>
        <div>
          <li class="nav-item dropdown">
            <a
              class="nav-link dropdown-toggle"
              href="#"
              role="button"
              data-bs-toggle="dropdown"
              aria-expanded="false"
            >
              <div class="d-inline-block position-relative">
                <i class="fa-solid fa-cart-shopping"></i>
                <span
                  class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger"
                >
                  {{cart.items|length|default:"0"}}
                  <span class="visually-hidden">unread messages</span>
                </span>
              </div>
            </a>
            <ul class="dropdown-menu m-0">
              <li class="p-3">
                <table
                  class="table caption-top table-borderless table-striped mb-0 align-middle text-center"
                >
                  <caption>
                    List of Products
                  </caption>
  
                  <thead class="">
                    <tr>
                      <th scope="col">#</th>
                      <th scope="col">Name</th>
                      <th scope="col">Price</th>
                      <th scope="col">Qty</th>
                      <th scope="col">Total</th>
                    </tr>
                  </thead>
                  <tbody class="table-group-divider">
                    {% for item in cart.items %}
                    <tr>
                      <th scope="row">{{forloop.counter}}</th>
                      <td class="text-left text-nowrap">
                        <a class="link-primary" href="{% url 'core:product_detail' item.product.id %}"
                          >{{item.product.name}}</a
                        >
                      </td>
                      <td>{{item.product.price}}</td>
                      <td>{{item.quantity}}</td>
                      <td class="text-right">{{item.total}}</td>
                    </tr>
                    {% empty %}
                    <tr>
                      <td class="text-left" colspan="5">Nothing found!</td>
                    </tr>
                    {% endfor %}
                  </tbody>
                </table>
              </li>
            </ul>
          </li>
        </div>    
      </ul>
      
      <ul class="navbar-nav me-1px mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link text-white" href="#">Cart</a>
        </li>
        <li class="nav-item">
          <a class="nav-link text-white" href="#">Orders</a>
        </li>
        <li class="nav-item dropdown">
          <a
            class="nav-link dropdown-toggle text-white"
            href="#"
            role="button"
            data-bs-toggle="dropdown"
            aria-expanded="false"
          >
          {{user}}
          </a>
          <ul class="dropdown-menu">
            {% if user.is_authenticated %}
            {% if user.profilemodel %}
            <li><a class="dropdown-item" href="{% url 'account:profile_detail' user.profilemodel.id %}">{{user}}</a></li>
            {% else %}
            <li><a class="dropdown-item" href="{% url 'account:profile_create' %}">{{user}}</a></li>
            {% endif %}
            <li><a class="dropdown-item" href="{% url 'account:logout' %}">Logout</a></li>
            {% else %}
            <li><a class="dropdown-item" href="{% url 'account:login' %}">Login</a></li>
            <li><a class="dropdown-item" href="{% url 'account:signup' %}">signup</a></li>
            {% endif %}
      </div>

</nav>

templates/includes/script.html
{% load static %}
<script src="{% static 'bootstrap-5.2.3-dist/js/bootstrap.bundle.js' %}"></script>
<script src="{% static 'fontawesome-free-6.2.1-web/js/all.js' %}"></script>
<script src="{% static 'js/script.js' %}"></script>

templates/includes/style.html
{% load static %}
<link rel="stylesheet" href="{% static 'bootstrap-5.2.3-dist/css/bootstrap.css' %}">
<link rel="stylesheet" href="{% static 'fontawesome-free-6.2.1-web/css/all.css' %}">
<link rel="stylesheet" href="{% static 'css/style.css' %}">