core/urls.py
from django.urls import path
from core import views

app_name = "core"
 
urlpatterns = [
    path("", views.HomeView.as_view(), name="home"),
    path("about/", views.AboutView.as_view(), name="about"),
    # product
    path("products/", views.ProductListView.as_view(), name="product_list"),
    path("products/create/", views.ProctCreateView.as_view(), name="product_create"),
    path("products/<int:pk>/", views.ProductDetailView.as_view(), name="product_detail"),
    path("products/find/", views.FindProductView.as_view(), name="find_product"),
    path("products/<int:pk>/update/", views.ProductUpdateView.as_view(), name="product_update"),
    path("products/<int:pk>/delete/", views.ProductDeleteView.as_view(), name="product_delete"),
    # feedback
    path("feedback/create", views.FeedbackCreateView.as_view(), name="feedback_create"),
    path("feedback/<int:pk>/detail/", views.FeedbackDetailView.as_view(), name="feedback_detail"),
     # Wishlist
    path("wishlists/add/product/<int:pk>/", views.AddToWishlistView.as_view(), name="add_to_wishlist"),
    path("wishlists/create/", views.WishlistCreateView.as_view(), name="wishlist_create"),
    path("wishlists/", views.WishlistListView.as_view(), name="wishlist_list"),
    #add to cart
    path("cart/add/product/<int:pk>/", views.AddToCartView.as_view(), name="add_to_cart"),
    #review
    path("reviews/add/product/<int:pk>/", views.ReviewCreatView.as_view(), name="review_create"),
    path("reviews/product/review/<int:pk>/", views.ReviewListView.as_view(), name="review_list"),

  
        

]

ecart/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("core.urls", namespace="core")),
    path("accounts/", include("account.urls", namespace="account")),
    path("", include("django.contrib.auth.urls")),

]
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

core/forms.py
from django import forms
from core import models


class ProductForm(forms.ModelForm):
    images = forms.ImageField(required=False)

    class Meta:
        model = models.ProductModel
        fields = ["name", "discription", "price", "unit", "category"]

class FeedbackForm(forms.ModelForm):
    
    class Meta :
        model = models.FeedbackModel
        fields = ["name","email","subject","message"]


class WishlistForm(forms.ModelForm):

    class Meta :
        model = models.WishlistModel
        fields = ["name"] 

class ProductImageForm(forms.ModelForm):

    class Meta:
        model =models.ProductImageModel
        fields =["path"]              

class Reviewform(forms.ModelForm):

    class Meta:
        model =models.ReviewModel
        fields =["comment","rating"]

   

core/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.views import generic as views
from core import models
from django.urls import reverse_lazy
from core import forms
from django.core.mail import send_mail
from django.conf import settings
from django.contrib.auth import mixins as auth_mixins


class HomeView(views.TemplateView):
    template_name = "core/home.html"
    extra_context = {
        "products": models.ProductModel.objects.all(),
    }


# this is exagiration of templateview

# class HomeView(views.View):
#     template_name = "core/home.html"
#     def get(self, request, *args):
#         context={
#            "project_name" :"Ecart"

#         }
#         return render(request,self.template_name,context)


class AboutView(views.TemplateView):
    template_name = "core/about.html"


# class ProductListView(views.ListView):
#     template_name = "core/products/product_list.html"
#     model = models.ProductModel
#     context_object_name = "products"


# this is exagiration of Listview


class ProductListView(views.View):
    template_name = "core/products/product_list.html"
    model = models.ProductModel
    context_object_name = "products"

    def get(self, request, *args):
        products = self.model.objects.all()
        context = {
            "products": products,
            "project_name": "Ecart",
            "page_name": "ProductList",
        }
        return render(request, self.template_name, context)


class ProctCreateView(views.CreateView):
    template_name = "core/products/product_create.html"
    model = models.ProductModel
    form_class = forms.ProductForm
    success_url = reverse_lazy("core:product_list")


# class ProductDetailView(views.DetailView):
#     template_name = "core/products/product_detail.html"
#     model =models.ProductModel
#     context_object_name ="product"


class ProductDetailView(views.View):
    template_name = "core/products/product_detail.html"
    model = models.ProductModel
    context_object_name = "product"

    def get(self, request, pk):
        product = self.model.objects.get(id=pk)
        context = {self.context_object_name: product}
        return render(request, self.template_name, context)


# class ProductUpdateView(views.UpdateView):
#     template_name = "core/products/product_update.html"
#     form_class = forms.ProductForm
#     model = models.ProductModel
#     success_url = reverse_lazy("core:product_list")


class ProductUpdateView(views.View):
    template_name = "core/products/product_update.html"
    model = models.ProductModel
    form_class = forms.ProductForm

    def get(self, request, pk):
        product = self.model.objects.get(id=pk)
        context = {"form": self.form_class(instance=product)}
        return render(request, self.template_name, context)

    def post(self, request, pk):
        product = self.model.objects.get(id=pk)
        form = self.form_class(request.POST, request.FILES, instance=product)
        if form.is_valid():
            return self.form_valid(form)
        return self.form_invalid(form)

    def form_valid(self, form):
        obj = form.save()
        return redirect(reverse_lazy("core:product_detail", args=(obj.id,)))

    def form_invalid(self, form):
        return render(self.request, self.template_name, {"form": form})


# class ProductDeleteView(views.DeleteView):
#     template_name = "core/products/product_delete.html"
#     model = models.ProductModel
#     success_url = reverse_lazy("core:product_list")


class ProductDeleteView(views.View):
    template_name = "core/products/product_delete.html"
    model = models.ProductModel
    success_url = reverse_lazy("core:product_list")

    def get(self, request, pk):
        product = self.model.objects.get(id=pk)
        cotext = {"product": product}
        return render(request, self.template_name, cotext)

    def post(self, request, pk):
        product = self.model.objects.get(id=pk)
        product.delete()
        # product.status=False
        # product.save()
        return redirect(self.success_url)


class FeedbackCreateView(views.CreateView):
    template_name = "core/feedback/feedback_create.html"
    model = models.FeedbackModel
    form_class = forms.FeedbackForm

    def form_valid(self, form):
        data = form.cleaned_data
        email_to = [
            data["email"],
        ]
        subject = "Thank you for your valuable feedback."
        message = f"""
        Hi {data['name']},
        we have received your feedback.we are
        so excited to reach you.stay turned.
                  
        Thank & regards
        Ecart team
        """
        from_email = settings.EMAIL_HOST_USER
        send_mail(subject, message, from_email, email_to, fail_silently=False)

        return super().form_valid(form)


class FeedbackDetailView(views.DetailView):
    template_name = "core/feedback/feedback_detail.html"
    model = models.FeedbackModel
    context_object_name = "feedback"


class FeedbackListView(views.ListView):
    template_name = "core/products/product_list.html"
    model = models.FeedbackModel
    context_object_name = "Feedback List"


# Wishlist related views
class AddToWishlistView(auth_mixins.LoginRequiredMixin, views.View):
    template_name = "core/wishlist/wishlist_list.html"

    def get(self, request, *args, **kwargs):
        wishlists = models.WishlistModel.objects.filter()
        product_id = kwargs.get("pk")
        product = models.ProductModel.objects.get(id=product_id)

        context = {
            "wishlists": wishlists,
            "product": product,
            "wishlist_form": forms.WishlistForm,
        }
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        wishlist_ids = request.POST.getlist("wishlist_id")

        product_id = kwargs.get("pk")
        product = models.ProductModel.objects.get(id=product_id)
        wishlists = models.WishlistModel.objects.filter(id__in=wishlist_ids)
        product.wishlistmodel_set.set(wishlists)

        url = request.META.get("HTTP_REFERER")
        return redirect(url, args=args, kwargs=kwargs)


class WishlistCreateView(auth_mixins.LoginRequiredMixin, views.CreateView):
    template_name = "core/wishlist/wishlist_create.html"
    model = models.WishlistModel
    fields = [
        "name",
    ]
    success_url = reverse_lazy("core:wishlist_list")

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class WishlistListView(auth_mixins.LoginRequiredMixin, views.ListView):
    template_name = "core/wishlist/wishlist_list.html"
    model = models.WishlistModel
    context_object_name = "wishlists"
    extra_context = {"wishlist_form": forms.WishlistForm}


# AddToCart related views


class AddToCartView(views.View):
    def get(self, request, *args, **kwargs):
        cart, cart_created = models.CartModel.objects.get_or_create(
            user=request.user, is_checked_out=False
        )
        product = models.ProductModel.objects.get(id=kwargs.get("pk"))
        cart_item, cart_item_created = models.CartItemModel.objects.get_or_create(
            product=product,
            cart=cart,
        )
        if cart_item_created:
            cart_item.quantity = 1
        else:
            cart_item.quantity += 1

        cart_item.save()
        url = request.META.get("HTTP_REFERER")
        return redirect(url)


class ReviewCreatView(views.CreateView):
    template_name = "core/review/review_create.html"
    model = models.ReviewModel
    form_class = forms.Reviewform

    def form_valid(self, form):
        image_form = forms.ProductImageForm(self.request.POST,self.request.FILES)
        if image_form.is_valid():
            image = image_form.save()

        product=models.ProductModel.objects.get(id=self.kwargs.get("pk"))
        form.instance.user = self.request.user
        form.instance.product = product
        review = form.save()
        review.images.set([image])
        review.save()

        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy("core:review_list", kwargs={"pk": self.kwargs.get("pk")})    

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({"image_form": forms.ProductImageForm,"product": models.ProductModel.objects.get(id=self.kwargs.get("pk"))})
        return context


class ReviewListView(views.ListView):
    template_name = "core/review/review_list.html"
    model = models.ReviewModel
    context_object_name = "reviews"  
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({"image_form": forms.ProductImageForm,"product": models.ProductModel.objects.get(id=self.kwargs.get("pk"))})
        return context
    
class FindProductView(views.ListView):
    template_name = "core/products/product_list.html"
    model = models.ProductModel
    context_object_name = "products"

    def get_queryset(self):
        qs = super().get_queryset()
        q = self.request.GET.get('q')
        qs = qs.filter(name__icontains=q)
        return qs

       

templates/core/products/product_create.html
{% extends "base.html" %} {% block content %}
<div class="container">
  <div class="row justify-center align-item-center">
    <div class="col-lg-6">
      <div class="card">
        <div class="card-body">
          <form method="post" enctype="multipart/form-data">
            {% csrf_token %} {{form.as_p}}
            <button class="btn btn-primary">create product</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}

templates/core/products/product_delete.html
{% extends "base.html" %} {% block content %}
<div class="container">
  <div class="row justify-center align-item-center">
    <div class="col-lg-6">
      <div class="card">
        <div class="card-body">
          <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <h5 class="text-danger">are you sure want to delete</h5>
            <button class="btn btn-primary">Delete product</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}

templates/core/products/product_detail.html
{% extends 'base.html' %} {% block content %}{% include "includes/navbar.html"%}
<div class="container product_detail_container d-none d-md-block">
  <div class="row h-100 pt-3">
    <div class="col-lg-6">
      <div
        id="carouselExampleControls"
        class="carousel slideve"
        data-bs-ride="carousel"
      >
        <div class="carousel-inner">
          {% for image in product.images.all %}
          <div class="carousel-item active">
            <img
              src="{{image.path.url}}"
              class="d-block"
              alt="item img "
              style="
                width: 100%;
                height: 600px;
                object-fit: scale-down;
                background-color: white;
              "
            />
          </div>
          {% endfor %}
        </div>
        <button
          class="carousel-control-prev bg-warning"
          type="button"
          data-bs-target="#carouselExampleControls"
          data-bs-slide="prev"
        >
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Previous</span>
        </button>
        <button
          class="carousel-control-next bg-warning"
          type="button"
          data-bs-target="#carouselExampleControls"
          data-bs-slide="next"
        >
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Next</span>
        </button>
      </div>
    </div>
    <div class="col-lg-6">
      <div><h4>{{product.name}}</h4></div>
      <div class="button-group-detail-b my-4">
        <a class="border-0 py-2 px-3" href="{% url 'core:add_to_wishlist' product.id  %}"
          ><i class="fa-solid fa-heart me-2"></i>ADD TO WISH LIST</a
        >
        <a class="border-0 py-2 px-1"href="{% url 'core:review_list' product.id  %}"
          ><i class="fa-solid fa-user me-2"></i>USER REVIEWS</a
        >
        <a class="border-0 py-2 px-1" href="{% url 'core:review_create' product.id  %}"
          ><i class="fa-solid fa-pen me-2"></i>WRITE A REVIEW</a
        >
        <a class="border-0 py-2 px-1"><i class="fa-solid fa-share me-2"></i>SHARE</a>
      </div>
      <div><p>{{product.discription}}</p></div>
      <div class="col d-flex">
        <h4>price:</h4>
        <h5 class="mt-1">INR {{product.price}}</h5>
      </div>
      <h5 class="text-warning col d-flex mt-3">
        <i class="fa-solid fa-star mt-1"></i
        ><i class="fa-solid fa-star mt-1"></i
        ><i class="fa-solid fa-star mt-1"></i
        ><i class="fa-solid fa-star-half-stroke mt-1"></i
        ><i class="fa-regular fa-star mt-1"></i>
        <div class="text-dark ms-2">(3.5 out of 5.0)(100)</div>
      </h5>
      <div class="col button-group-detail-a my-4">
        <a class="bg-success border-0 text-white px-3 py-2 me-2">
          <i class="fa-solid fa-circle-down me-2"></i>BUY NOW
        </a>
        <a
          class="bg-danger border-0 text-white px-3 py-2"
          href="{% url 'core:add_to_cart' product.id %}"
          ><i
            class="fa-solid fa-cart-shopping display-2 mt-1 me-2"
            style="font-size: 16px"
          ></i
          >ADD TO CART</a
        >
      </div>
      <div class="row mt-1 detail_comment">
        <div class="col-6">
          <div class="card">
            <div class="card-body">
              <h4>Jinto</h4>
              <p>
                “I am so impressed with the quality of the vegetables in this
                kit! They are all so fresh and delicious. The variety of
                vegetables included is also great, I've been able to try new
                things and expand my cooking horizons.
              </p>
              <h6 class="text-warning col d-flex mt-3">
                <i class="fa-solid fa-star mt-1"></i
                ><i class="fa-solid fa-star mt-1"></i
                ><i class="fa-solid fa-star mt-1"></i
                ><i class="fa-solid fa-star-half-stroke mt-1"></i
                ><i class="fa-regular fa-star mt-1"></i>
                <div class="text-dark ms-2">(3.5 out of 5.0)(100)</div>
              </h6>
              <div class="col d-flex gap-1">
                <button class="bg-success border-0 text-white px-3 py-2">
                  <i class="fa-solid fa-thumbs-up me-2"></i>Useful
                </button>
                <button class="bg-danger border-0 text-white px-3 py-2">
                  <i class="fa-solid fa-thumbs-down me-2"></i>Not Useful
                </button>
              </div>
            </div>
          </div>
        </div>
        <div class="col-6">
          <div class="card">
            <div class="card-body">
              <h4>Jinto</h4>
              <p>
                “I am so impressed with the quality of the vegetables in this
                kit! They are all so fresh and delicious. The variety of
                vegetables included is also great, I've been able to try new
                things and expand my cooking horizons.
              </p>
              <h6 class="text-warning col d-flex mt-3">
                <i class="fa-solid fa-star mt-1"></i
                ><i class="fa-solid fa-star mt-1"></i
                ><i class="fa-solid fa-star mt-1"></i
                ><i class="fa-solid fa-star-half-stroke mt-1"></i
                ><i class="fa-regular fa-star mt-1"></i>
                <div class="text-dark ms-2">(3.5 out of 5.0)(100)</div>
              </h6>
              <div class="col d-flex gap-1">
                <button class="bg-success border-0 text-white px-3 py-2">
                  <i class="fa-solid fa-thumbs-up me-2"></i>Useful
                </button>
                <button class="bg-danger border-0 text-white px-3 py-2">
                  <i class="fa-solid fa-thumbs-down me-2"></i>Not Useful
                </button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="container product_detail_container d-md-none">
  <div class="row h-100 pt-3">
    <div class="col-sm-12">
      <div
        id="carouselExampleControls"
        class="carousel slideve"
        data-bs-ride="carousel"
      >
        <div class="carousel-inner">
          {% for image in product.images.all %}
          <div class="carousel-item active">
            <img
              src="{{image.path.url}}"
              class=""
              alt="item img "
              style="
                width: 100%;
                height: 200px;
                object-fit: scale-down;
                background-color: white;
              "
            />
          </div>
          {% endfor %}
        </div>
        <button
          class="carousel-control-prev bg-warning"
          type="button"
          data-bs-target="#carouselExampleControls"
          data-bs-slide="prev"
        >
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Previous</span>
        </button>
        <button
          class="carousel-control-next bg-warning"
          type="button"
          data-bs-target="#carouselExampleControls"
          data-bs-slide="next"
        >
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Next</span>
        </button>
      </div>
    </div>
    <div class="col-lg-6">
      <div class=""><h4>{{product.name}}</h4></div>
      <div
        class="col-12 button-group-detail-b my-4 d-flex align-items-center justify-content-center gap-2 "
      >
        <div class="col-6">
          <a class="border-0 w-100 py-2 px-3 ms-5" href="{% url 'core:add_to_wishlist' product.id %}" >
            <i class="fa-solid fa-heart me-2"></i>ADD T O WISH LIST
          </a>
        </div>
        <div class="col-6">
          <a class="border-0 w-100 py-2 px-5">
            <i class="fa-solid fa-share me-2"></i>SHARE
          </a>
        </div>
      </div>
      <div class="cart" style="display: hiden">
        <div><p>{{product.discription}}</p></div>
      </div>
      <div class="col d-flex">
        <h1>price:</h1>
        <h5 class="mt-2">INR {{product.price}}</h5>
      </div>
      <h5 class="text-warning col d-flex mb-3">
        <i class="fa-solid fa-star mt-1"></i
        ><i class="fa-solid fa-star mt-1"></i
        ><i class="fa-solid fa-star mt-1"></i
        ><i class="fa-solid fa-star-half-stroke mt-1"></i
        ><i class="fa-regular fa-star mt-1"></i>
        <div class="text-dark ms-2">(3.5 out of 5.0)(100)</div>
      </h5>
      <div
        class="col-12 button-group-detail-b d-flex align-items-center justify-content-center gap-2"
      >
        <div class="col-6">
          <a class="border-0 w-100 py-2 px-5 ms-2">
            <i class="fa-solid fa-user me-2"></i>USER REVIEWS
          </a>
        </div>
        <div class="col-6 ms-3">
          <a class="border-0 w-100 py-2 px-4">
            <i class="fa-solid fa-pen me-2"></i>WRITE A REVIEW
          </a>
        </div>
      </div>
      <div
        class="col-12 button-group-detail-a my-4 d-flex justify-content-center align-items-center"
      >
        <div class="col-6">
          <a class="bg-success border-0 text-white px-3 py-2 px-5 w-100 ms-4">
            <i class="fa-solid fa-circle-down me-2"></i>BUY NOW
          </a>
        </div>
        <div class="col-6">
          <a class="bg-danger border-0 text-white px-4 py-2 w-100">
            <i
              class="fa-solid fa-cart-shopping display-2 mt-1 me-2"
              style="font-size: 16px"
            ></i
            >ADD TO CART
        </a>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}

templates/core/products/product_list.html
{% extends 'base.html' %} {% block content %} {% include "includes/navbar.html"%}


<div class="container product_list">
  <div class="row">
    <div class="col">
      <div class="">
        <form class="d-flex p-head-1" method="get" action="{% url 'core:find_product' %}">
          <input
          type="search"
          class="search-p mt-2"
          placeholder="Type product name, category or anything here..."
          aria-label="Search"
          name="q"
        />
        <button class="btn btn-success s-button mb-2">
          <i class="fa-solid fa-magnifying-glass text-white me-2"></i>Find
          Products
        </button>
        </form>
       
      </div>
      <div
        class="d-md-flex align-items-center justify-content-between p-head-2"
      >
        <h2 class="mt-5 mb-4">Search results</h2>
        <button class="mt-5 f-button">
          Filter<i class="fa-solid fa-sliders ms-2"></i>
        </button>
      </div>
      <div class="p-head-3 d-md-none">
        <h2 class="mt-5 mb-4">Popular Products</h2>
      </div>
    </div>
  </div>
  <div class="row row-cols-lg-4 row-cols-1 g-3">
    {% for product in products %}
    <div class="col">
      <div class="card">
        {% for image in product.images.all %}
        <img
          height="200px"
          width="200px"
          src="{{image.path.url}}"
          class="card-img-top"
          style="width: 100; object-fit: scale-down; background-color: white"
        />
        {% endfor %}
        <div class="card-body">
          <a
            class="card-title"
            href="{% url 'core:product_detail' product.id %}"
            ><h5>{{product.name|truncatewords:"10"}}</h5></a
          >

          <p class="card-text mt-3">{{product.discription|truncatewords:"10"}}</p>
          <h5 class="card-text-1 my-3">INR{{product.price}}</h5>
          <h5 class="text-warning col d-flex mb-4">
            <i class="fa-solid fa-star"></i><i class="fa-solid fa-star"></i
            ><i class="fa-solid fa-star"></i
            ><i class="fa-solid fa-star-half-stroke"></i
            ><i class="fa-regular fa-star"></i>
            <div class="text-dark">(3.5 out of 5.0)</div>
          </h5>
          <div
            class="d-flex align-items-center justify-content-center gap-2 flex-wrap"
          >
            <a href="#" class="btn btn-success w-100 buy"
              ><i class="fa-solid fa-circle-down"></i> BUY NOW</a
            >
            <a href="#" class="btn btn-danger w-100 cart">
              <i
                class="fa-solid fa-cart-shopping display-2 mt-1 me-2"
                style="font-size: 16px"
              ></i
              >ADD TO CART</a
            >
          </div>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
</div>

{% endblock %}

<a href="{% url 'core:product_delete' product.id %}" class="btn btn-secondary"
  >Delete</a
>
<a href="{% url 'core:product_update' product.id %}" class="btn btn-secondary"
  >update</a
>

templates/core/products/product_update.html
{% extends "base.html" %} {% block content %}
<div class="container">
  <div class="row justify-center align-item-center">
    <div class="col-lg-6">
      <div class="card">
        <div class="card-body">
          <form method="post" enctype="multipart/form-data">
            {% csrf_token %} {{form.as_p}}
            <button class="btn btn-primary">update product</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}